version: "3.8"

services:
  web:
    build:
      args:
        - USER_ID=1000
      context: .
      dockerfile: Dockerfile
    image: webapp
    container_name: webcontainer
    ports:
      - 80:80
    volumes:
      # - appvol:/var/www/html/
      - ./src:/var/www/html/
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      # - /var/www/html/vendor
      # - /var/www/html/node_modules
    networks:
      - webapp_network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webapp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpdbadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - webapp_network

networks:
  webapp_network:

volumes:
  mysql_data:
  appvol:
